/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_TELEMETRY_TELEMETRY_SERVICE_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_TELEMETRY_TELEMETRY_SERVICE_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/telemetry/TelemetryServiceStub.hpp>
#include <v1/commonapi/telemetry/TelemetryServiceSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace telemetry {

template <typename _Stub = ::v1::commonapi::telemetry::TelemetryServiceStub, typename... _Stubs>
class TelemetryServiceSomeIPStubAdapterInternal
    : public virtual TelemetryServiceStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< TelemetryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> TelemetryServiceSomeIPStubAdapterHelper;

    ~TelemetryServiceSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        TelemetryServiceSomeIPStubAdapterHelper::deinit();
    }

    void fireTelemetryUpdateEvent(const ::v1::commonapi::telemetry::TelemetryService::SourceType &_source, const float &_loadValue);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::telemetry::TelemetryServiceStub,
        CommonAPI::Version
    > getTelemetryServiceInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::telemetry::TelemetryServiceStub,
        std::tuple< TelemetryService::SourceType>,
        std::tuple< float, bool>,
        std::tuple< ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t>,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment>
    > getLoadStubDispatcher;
    
    TelemetryServiceSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        TelemetryServiceSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< TelemetryServiceStub>(_stub)),
        getTelemetryServiceInterfaceVersionStubDispatcher(&TelemetryServiceStub::lockInterfaceVersionAttribute, &TelemetryServiceStub::getInterfaceVersion, false, true),
        getLoadStubDispatcher(
            &TelemetryServiceStub::getLoad,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
        
    {
        TelemetryServiceSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &getLoadStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x1));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8001), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void TelemetryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTelemetryUpdateEvent(const ::v1::commonapi::telemetry::TelemetryService::SourceType &_source, const float &_loadValue) {
    CommonAPI::Deployable< TelemetryService::SourceType, ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t> deployed_source(_source, static_cast< ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< ::v1::commonapi::telemetry::TelemetryService::SourceType, ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t > 
    ,  float
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8001),
            false,
             deployed_source 
            , _loadValue
    );
}


template <typename _Stub, typename... _Stubs>
void TelemetryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void TelemetryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::commonapi::telemetry::TelemetryServiceStub, typename... _Stubs>
class TelemetryServiceSomeIPStubAdapter
    : public TelemetryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    TelemetryServiceSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          TelemetryServiceSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace telemetry
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_TELEMETRY_Telemetry_Service_SOMEIP_STUB_ADAPTER_HPP_
