/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_TELEMETRY_TELEMETRY_SERVICE_HPP_
#define V1_COMMONAPI_TELEMETRY_TELEMETRY_SERVICE_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace telemetry {

class TelemetryService {
public:
    virtual ~TelemetryService() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct SourceType : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            CPU = 0,
            RAM = 1,
            GPU = 2
        };
    
        SourceType()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::CPU)) {}
        SourceType(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::CPU):
                case static_cast< uint8_t>(Literal::RAM):
                case static_cast< uint8_t>(Literal::GPU):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SourceType &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SourceType &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SourceType &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SourceType &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SourceType &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SourceType &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::CPU): return "CPU";
            case static_cast< uint8_t>(Literal::RAM): return "RAM";
            case static_cast< uint8_t>(Literal::GPU): return "GPU";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* TelemetryService::getInterface() {
    return ("commonapi.telemetry.TelemetryService:v1_0");
}

CommonAPI::Version TelemetryService::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace telemetry
} // namespace commonapi
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TELEMETRY_TELEMETRY_SERVICE_HPP_
