/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/telemetry/TelemetryServiceSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace telemetry {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createTelemetryServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< TelemetryServiceSomeIPProxy>(_address, _connection);
}

void initializeTelemetryServiceSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.telemetry.TelemetryService:v1_0:commonapi.telemetry.TelemetryService",
        0x1234, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.telemetry.TelemetryService:v1_0",
        &createTelemetryServiceSomeIPProxy);
}

INITIALIZER(registerTelemetryServiceSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeTelemetryServiceSomeIPProxy);
}

TelemetryServiceSomeIPProxy::TelemetryServiceSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          telemetryUpdate_(*this, 0x1, CommonAPI::SomeIP::event_id_t(0x8001), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
{
}

TelemetryServiceSomeIPProxy::~TelemetryServiceSomeIPProxy() {
}


TelemetryServiceSomeIPProxy::TelemetryUpdateEvent& TelemetryServiceSomeIPProxy::getTelemetryUpdateEvent() {
    return telemetryUpdate_;
}

void TelemetryServiceSomeIPProxy::getLoad(TelemetryService::SourceType _source, CommonAPI::CallStatus &_internalCallStatus, float &_loadValue, bool &_success, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< TelemetryService::SourceType, ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t> deploy_source(_source, static_cast< ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_loadValue(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_success(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                TelemetryService::SourceType,
                ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >,
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_source,
        _internalCallStatus,
        deploy_loadValue, deploy_success);
    _loadValue = deploy_loadValue.getValue();
    _success = deploy_success.getValue();
}

std::future<CommonAPI::CallStatus> TelemetryServiceSomeIPProxy::getLoadAsync(const TelemetryService::SourceType &_source, GetLoadAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< TelemetryService::SourceType, ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t> deploy_source(_source, static_cast< ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_loadValue(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_success(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                TelemetryService::SourceType,
                ::v1::commonapi::telemetry::TelemetryService_::SourceTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >,
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_source,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< float, CommonAPI::EmptyDeployment > _loadValue, CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment > _success) {
            if (_callback)
                _callback(_internalCallStatus, _loadValue.getValue(), _success.getValue());
        },
        std::make_tuple(deploy_loadValue, deploy_success));
}

void TelemetryServiceSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> TelemetryServiceSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace telemetry
} // namespace commonapi
} // namespace v1
